### ISSUE TITLE
Maybe a bug with the error "Cannot dispatch in the middle of a dispatch."

### ISSUE THREAD

**Issue by fabiozaffani** [facebook/flux#106]
Hi,

Currently I have the following order of events, which are causing this error to occur:

1. User click's a button to add a product to a cart (the button calls action creator and send ADD_ITEM event, which will be send throught the dispatcher to te stores);
2. The cart store get this event and update with the product data sended throught the action;
3. At the same time an API at the UTIL folder calls an async operation to write that update to the server

For testing purposes i'm simulating an local API, which makes the response be imediately.The idea is that the API will dispatch another event through the action creator once the response from the server arrives, something like ADD_ITEM_SUCCESS or ADD_ITEM_ERROR should be dispatched throught the action creator. Currently that's the precisely moment when the error happens, i'm guessing that's because there are almost no delay between the ADD_iTEM and the response from the server event (SUCCESS or ERROR).

However, if I encapsulate the code in a setTimeout function everything works fine, even if I set the timeOut to be at only 1ms or 0. Which leaves me thinking if that might be a bug in the currently version of the dispatcher?

**Comment by vladar** [comment]
There is a great concept of Statecharts (or UML State Machines) which has some similarities with Flux. It is kind of stuck in academia world, but is well established technology and tested for decades.

One of the similarities with Flux is the dispatch process. They call it RTC (run to completion):

"In the RTC model, the system processes events in discrete, indivisible RTC steps. New incoming events cannot interrupt the processing of the current event and must be stored (typically in an event queue) until the state machine becomes idle again. These semantics completely avoid any internal concurrency issues within a single state machine. The RTC model also gets around the conceptual problem of processing actions associated with transitions, where the state machine is not in a well-defined state (is between two states) for the duration of the action."

http://en.wikipedia.org/wiki/UML_state_machine#Run-to-completion_execution_model

So it is basically the same as Flux dispatch cycle, with one major difference: nested dispatches are allowed, but they are added to (sync) queue and dispatched only after current dispatch cycle is complete. 

The problem with Flux dispatcher right now is that sometimes you really need to fire some action in response to other action (and this is perfectly valid case in Statecharts too). 

In some cases these actions are created in async handlers (e.g. web api utils). So it kinda works because it doesn't interfere with current dispatch cycle. But why would you allow async operation from store and disallow sync one?

Only because sync operations may interfere with current dispatch process (when your app is in non-consistent state).

I think RTC approach and sync queue solves this problem and doesn't add as much complexity or external dependencies to code as async queue.

**Comment by fisherwebdev** [comment]
That's actually not the reasoning as to why we disallow the dispatch-within-a-dispatch.

The reason is that we are interested in preventing cascading updates.  This is the primary problem that causes complexity in the data layer, leading it to become difficult for engineers to reason about how application state is changing.

The Flux perspective is that a mutation should not cause another mutation.  Instead, mutations are passive, merely responding to things happening "outside" of the application -- the user clicks, the server responds, the browser cycles an animation frame, etc.

We've talked about and experimented with creating an action queue in front of the dispatcher, but we've stopped short of going forward with it, as it leads immediately to these cascading updates.

**Comment by sompylasar** [comment]
@fisherwebdev So how do you cope with cascading updates that should happen within the application? Do you fire subsequent actions from stores in a setTimeout callback which in fact relies on the JavaScript internal event queue?

**Comment by sterpe** [comment]
@sompylasar I've often found that "cascading" updates can often be handled alternatively like so without need to use `setTimeout`:

```
someActionCreator.action = function () {
  dispatcher.dispatch({ actionType: "A"...});
  dispatcher.dispatch({ actionType: "B"...});
  ...
};
```

There won't be a browser repaint until the thread is free.

However, @fisherwebdev, @zpao I'm not sure if this is a good, bad, or ugly practice?  Does FB code do this at all or is it just better to merge sequential dispatches 'A' & 'B' above into a third dispatch 'C' which conglomerates them?

**Comment by fisherwebdev** [comment]
@sterpe Those sequential calls to dispatch are happening synchronously.  They are separate dispatches, so yes this works fine.  However, I've never seen that done at FB, and I'm not sure why anyone would do that.  We would simply merge them, as you suggested.

@sompylasar We believe that cascading actions are a sign of a design problem, and we avoid them entirely.  When all stores are receiving all actions, it's often trivial to simply respond to the original action and `waitFor()` anything that needs to happen first.

**Comment by sterpe** [comment]
Thanks

**Comment by mkrn** [comment]
If anyone is interested I've modified the @fabiozaffani 's dispatcher to work without `async` and it solved all of our `Cannot dispatch in the middle of dispatch` problems. 

In our case components that had their data loaded in store were displaying components that in their turn threw actions to load their content, so that caused the error. Queue solves it and order remains the same.

Here's the code:
Note that it's not implementing 2 methods `handleServerAction` and `handleViewAction` but just `handleAction`. It is using tiny sync-queue dependency. https://github.com/tessel/sync-queue 

```
'use strict';

import Flux from 'flux';
import assign from 'react/lib/Object.assign';
import Queue from 'sync-queue';

let queue = new Queue();

let Dispatcher = assign(new Flux.Dispatcher(), {
  handleAction (action, data) {

    let payload = {};

    payload = assign(
      {
        event: action
      },
      data
    );

    queue.place(() => {
      
      this.dispatch(payload);
      queue.next();
    }); 
  }
});

export default Dispatcher;
```

**Comment by tonyjmnz** [comment]
I have a similar situation to @mkrn's, I have a component that can have anywhere from 4-8 child components that each trigger an action to load their own data. When one of those `FETCH_DATA` actions gets dispatched at the same time as a previous request's `SUCCESS` action I get the `"Cannot dispatch in the middle of a dispatch."` error.

I'm wondering if there's a better way for achieving this, for now I think I will go with @mkrn's solution.

**Comment by hankgalt** [comment]
How about following as a solution? 

`var Dispatcher = require('flux').Dispatcher;
var appDispatcher = new Dispatcher();

appDispatcher.handleAction = function(action) {
  this.dispatch({
    source: 'VIEW_ACTION',
    action: action
  });
};

appDispatcher.dispatch = function(dispatchAction) {
  if ( this.isDispatching() ) {
  	this._pendingDispatches = this._pendingDispatches || [];
  	this._pendingDispatches.push(dispatchAction);
  } else {
  	Dispatcher.prototype.dispatch.call(this, dispatchAction);
  }
}

appDispatcher._stopDispatching = function() {
	var pendingDispatch;

	Dispatcher.prototype._stopDispatching.call(this);
  if (this._pendingDispatches && this._pendingDispatches.length > 0) {
  	pendingDispatch = this._pendingDispatches.shift();
  	Dispatcher.prototype.dispatch.call(this, pendingDispatch);
  }
}

module.exports = appDispatcher;`
