### ISSUE TITLE
Allow subscribing to only certain dispatch types from the dispatcher

### ISSUE THREAD

**Issue by parris** [facebook/flux#237]
Let me preface by saying, maybe I'm misunderstanding some key concept, and that I'm partially requesting this feature to get some clarification. I understand that there is probably some intent here.

In lots of pub/sub systems you can subscribe to specific events or action types. Here is the backbone flavor of that sort of thing:

    this.listenTo(dispatcher, myActionName, myCallback);

This adds a callback and context to an array containing all interested parties in that message. The resulting object might look like this:

    dispatcher = {
        actionMap: {
            'myActionName': [
                {
                    callback: ...,
                    context: ...
                },
                {
                    callback: ...,
                    context: ...
                }
            ],
            'mySecondActionName': []
        }    
    }

If flux adopted something like this you may have a couple key benefits: 
1) Dispatching no longer notifies every object of everything occurring throughout the system and instead only messages parties interested in specific message types. This means for really large systems with lots of objects not everyone is listening to everything.
2) Normalization of how objects are created and destroyed. Namely, you could destroy a store or anything else listening and the `unregister` could happen automatically.

I realize there are some negatives. Perhaps this is a design decision to force listeners to just be stores and only have a handful of them. If you implement the above it allows any view anywhere to listen to any dispatched thing. Is that something that flux is specifically trying to avoid? Are ViewControllers even allowed to listen to the dispatcher?

**Comment by kyldvs** [comment]
It's an intentional decision to have every action be sent to all of the callbacks registered with the dispatcher. It makes it harder to mess something up, in your store every single thing that could happen you have a chance to respond to. When you want to start responding to another action you don't really have to think about it, you just add it to your switch because you can be confident every action will be sent to every store.

Regarding your specific points:

1) Have you noticed scaling issues with this approach? We have well over 200 stores in our system (probably about a thousand actions) and the length of a dispatch on average (including handling the action logic!) is 8ms

2) Not sure I follow this exactly. There is an unregister method on dispatcher, is that what you are wanting here?

**Comment by kyldvs** [comment]
No response for a while, feel free to re-open if you have any other questions!

**Comment by parris** [comment]
Yea sorry about the non-response. I guess I just started understanding flux a bit better.

1) No scaling issues so far, but I could have seen it with our original approach. We were hooking up the dispatcher to views as well. 
2) Typically in backbone applications when you call "destroy", and get rid of a model, anything listening to that model gets unbound and all events are disconnected. I was proposing that unregister could happen automatically. That being said, I can't see stores really being destroyed.

Follow up question: I understand that stores are supposed to represent a problem domain. However, it is a bit hard trying to explain what the boundaries/responsibilities of a store are. Is there a good rule of thumb or set of rules to help with this concept?

**Comment by kyldvs** [comment]
Check out the documentation here: http://facebook.github.io/flux/docs/flux-utils.html it lists some best practices that might help you.
