### ISSUE TITLE
Why are you using a switch statement?

### ISSUE THREAD

**Issue by Lenne231** [facebook/flux#242]
Is there a reason why you are using a `switch` statement in the registered callback? Why not multiple callbacks, one for each action type.
``` 
AppDispatcher.register(TodoConstants.TODO_CREATE, function(action) { ... }); 
AppDispatcher.register(TodoConstants.TODO_COMPLETE, function(action) { ... }); 
```
instead of
```
AppDispatcher.register(function(action) {
  switch(action.actionType) {
    ...
  }
});
```

**Comment by sprjr** [comment]
A lot of folks I've seen have written something more along the lines of registering a callback per instead of the switch. I did the same in `flux-utils` to help facilitate that. I don't know that there is a specific reason for the switch in the example other than it's a simple way to keep all the code in one place for example purposes - I could be wrong but I don't think it's intended as the "way to do things."

**Comment by kyldvs** [comment]
The dispatcher doesn't really lock you into the switch. For example you could construct your base store like this and have each action type map to a specific callback in your store: https://gist.github.com/kyldvs/9de4c5d020b46a2d45e7

That said I do prefer the switch for controlling the flow of my stores, and I believe it's more performant according to: https://github.com/facebook/flux/pull/35#issuecomment-52846211

**Comment by kyldvs** [comment]
Along with #243 a switch statement allows strong type checking as well.

Closing this out since nothing about this repo forces you to use a switch, it's just what we recommend.
