### ISSUE TITLE
Move each example to a separate repository

### ISSUE THREAD

**Issue by gajus** [facebook/flux#246]
Contributing to the existing examples is complicated because issues and pull requests mix in with the flux base repository. Move the existing examples to individual repositories and create an EXAMLES.md reference.

**Comment by kyldvs** [comment]
I don't think it's that complex. I like having them all in the same directory so they are easy to find, and so that when modifying Flux you can ensure you do not break examples by referencing the local copy of Flux, https://github.com/facebook/flux/blob/master/examples/flux-utils-todomvc/package.json#L9

React also follows this model, so I doubt we will deviate from them: https://github.com/facebook/react/tree/master/examples
