### ISSUE TITLE
Flux utils: What is the purpose of making calculateState a static method?

### ISSUE THREAD

**Issue by tarrsalah** [facebook/flux#275]
By making the `calculateState` method **static** in the `Container` class, I can't access to `this.props` from this method (When I'm using `react-router` for example, I need to access to `this.props.params`).

**Comment by kyldvs** [comment]
It's important to make it static so that you do not access this.props without hooking into the correct lifecycle methods, in particular when using props within calculateState you must update the state when `componentWillReceiveProps` happens.

If you need to access props within `calculateState()` pass `{withProps: true}` to `Container.create()`, see the documentation here: http://facebook.github.io/flux/docs/flux-utils.html#container

**Comment by longtk** [comment]
How about calling Container in Container ? I need to pass props from Container A to B .
