### ISSUE TITLE
Flux and a complex action chain question

### ISSUE THREAD

**Issue by luisherranz** [facebook/flux#287]
Hi there,

Consider the following scenario. We have an app with a router:
- Each time the user clicks a link, we catch it and dispatch an action, for example, clicking on `"/profile"` dispatches `"SHOW_PROFILE"` (and we update the url as well, of course).
- We have **Stores** which register to those `"SHOW_PAGE"` actions to do stuff. For example, **_analyticsStore**_ which sends events to your analytics solution or **_breadcrumbsStore**_ which updates the breadcrumb with the actual page info.

So far, so well. But when a new user creates an account, it is a redirected to a new screen called `AddNameAndCreateFirstPost`. In that screen...
- The user enters his own name.
- The user enters the content of his first Post.
- The user clicks the `Submit` button.

_BTW, I'm using optimistic UI updates here, so everything is sync._

When the user clicks that `Submit` button, we need to store his name in the **_userStore**_, store the new Post in the **_postsStore**_ and redirect him to the dashboard.

The **Stores** are currently registered to these actions, used among the app:
- **_userStore**_ is registered to `"UPDATE_USER_NAME"` to change the name.
- **_postsStore**_ is registered to `"NEW_POST_CREATED"` to add new posts.
- **_analyticsStore**_ is registered to `"SHOW_DASHBOARD"` to send analytics.
- **_breadcrumbsStore**_ is registered to `"SHOW_DASHBOARD"` to change the breadcrumb.

I see these possible implementations:
- When user clicks `Submit` we dispatch `"CREATE_FIRST_POST_FORM_SUBMITTED"`. 
  This makes sense, is what the user did, but we will have to change all our **Stores** and add that `"CREATE_FIRST_POST_FORM_SUBMITTED"` action when they register to `"UPDATE_USER_NAME"`, `"NEW_POST_CREATED"` or `"SHOW_DASHBOARD"`. 
  This is really ugly and couples the **Stores** to too-specific actions. I am sure when the app grows somebody will add a new **Store** and will forget to register to the `"CREATE_FIRST_POST_FORM_SUBMITTED"` action when he is registering to `"UPDATE_USER_NAME"`, `"NEW_POST_CREATED"` or `"SHOW_DASHBOARD"`.
- When user clicks `Submit` we dispatch three actions, one after another to avoid the `Cannot dispatch in the middle of a dispatch` restriction. First `"UPDATE_USER_NAME"`, then `"NEW_POST_CREATED"` and finally `"SHOW_DASHBOARD"`.

``` javascript
// ...
  Dispatcher.dispatch({ actionType: "UPDATE_USER_NAME", userName: ... });
  Dispatcher.dispatch({ actionType: "NEW_POST_CREATED", postContent: ... });
  Dispatcher.dispatch({ actionType: "SHOW_DASHBOARD" });
```

This second implementation seems ok, but I have never seen dispatching more than one action in any Flux example, so I am suspicious. Besides, we are making flow decisions in the UI (are we?), not sure if that is right as well.

I am wondering if I am missing something and this could be addressed in some other way. I have researched a lot but I have not seen any good Flux and Router examples, where the router actually dispatch actions and after some action you need to redirect the user to another page.

Thanks in advance!

**Comment by sterpe** [comment]
See comment and response here:  https://github.com/facebook/flux/issues/106#issuecomment-104922886

**Comment by LuisHerranz** [comment]
Thanks @sterpe.

@fisherwebdev said this in that thread:
*"@sterpe Those sequential calls to dispatch are happening synchronously. They are separate dispatches, so yes this works fine. However, I've never seen that done at FB, and I'm not sure why anyone would do that. We would simply merge them, as you suggested."*

So I still have the doubt of which implementation is better, or if there is another I didn't think about.

**Comment by kyldvs** [comment]
Why is merging of the actions strange to you? Generally an action fired should correspond to what the user is doing, it doesn't correspond to what you want a store to do.

This doesn't mean you have to duplicate logic in many places though, for common things you can pull it out into helper functions. Consider for a moment if you had one giant store, your action handling may look this:

```javascript
reduce(state, action) {
  switch (action.type) {
    case 'change_username':
      return updateUserName(state, action.userName);

    case 'create_first_post_form_submitted':
      state = updateUserName(state, action.userName);
      state = newPostCreated(state, action.postContent);
      state = showDashboard(state);
      return state;

    case 'dashboard_clicked':
      return showDashboard(state);
  }

  return state;
}
```

Here we don't duplicate the logic for common things an action may do. We do have a clear list of things the user can do, and then for each of those things a list of how it affects the state.

**Comment by kyldvs** [comment]
We have also run into cases where firing multiple actions synchronously has broken the UI. What tends to happen is someone assumes that a button being clicked will cause one chunk of work to happen and then not handle intermediate states. Something like

```javascript
dispatch({type: 'set_tab', tab: 'dashboardTab'});

// let's pretend props.dashboard is null until after this action
dispatch({type: 'select_default_dashboard'});

// This is the component that is rendered when the dashboard is rendered
function DashboardView(props) {
  const {dashboard} = props;
  return (
    <div>
      <h1>{dashboard.name}</h1>
      <div>{renderDashboardContent(dashboard.content)}</div>
    </div>
  );
}
```

In the render function it is perfectly reasonable to assume that when rendering the dashboard view there is some dashboard that exists. And it kind of appears safe because the default dashboard is set immediately after switching to this view. However; it will cause an exceptions because as soon as that first dispatch happens the react tree will re-render with an inconsistent view of your stores.

This scenario has played out a few times for us. It's usually been hard to detect because it worked at first, but then while refactoring parts of our flux infrastructure all of these places started breaking.

The two solutions are to either always dispatch exactly one thing describing the entire action that is taking place, or write logic to safely handle intermediate steps that may happen in your application. Generally we have preferred the former.

**Comment by sterpe** [comment]
@kyldvs I eventually ran into that too.

**Comment by LuisHerranz** [comment]
Many thanks for your answer @kyldvs. 

*I hope you get my answer as a constructive argument. I don't mean to be rude questioning yours. I really want to get a better understanding of this case and it's possible implications and I hope it helps other people with the same problem as well.*

What is bugging me about "merging several actions" into one is that you have to remember a lot of specific actions, which doesn't describe what is really happening.

If you have one giant store, like you wrote, it is clear what is happening and easier to debug. But when the app grows, I think this may lead to problems. 

Think about the `"SHOW_DASHBOARD"` action, for example. Imagine it's used in 10 different **Stores**. And imagine we merge a lot of more actions like this, which they end up redirecting the user to the dashboard. It's quite possible that you end up having something like this:

```javascript
// analyticsStore.js
Dispatcher.register(function(payload){
  switch(payload.actionType) {
    case 'SHOW_DASHBOARD':
    case 'CREATE_FIRST_POST_FORM_SUBMITTED':
    case 'LOGIN_SUCCESSFUL':
    case 'CURRENT_POST_DELETED':
    case 'CURRENT_PAGE_DELETED':
    case 'UPDATE_FINISHED':
      sendDashboardAnalytics();
      break;
    ...
  };
});

// breadcrumbsStore.js
Dispatcher.register(function(payload){
  switch(payload.actionType) {
    case 'SHOW_DASHBOARD':
    case 'CREATE_FIRST_POST_FORM_SUBMITTED':
    case 'LOGIN_SUCCESSFUL':
    case 'CURRENT_POST_DELETED':
    case 'CURRENT_PAGE_DELETED':
    case 'UPDATE_FINISHED':
      changeBreadcrumbs('dashboard');
      break;
    ...
  };
});

// renderStore.js
Dispatcher.register(function(payload){
  switch(payload.actionType) {
    case 'SHOW_DASHBOARD':
    case 'CREATE_FIRST_POST_FORM_SUBMITTED':
    case 'LOGIN_SUCCESSFUL':
    case 'CURRENT_POST_DELETED':
    case 'CURRENT_PAGE_DELETED':
    case 'UPDATE_FINISHED':
      renderDashboard();
      break;
    ...
  };
});

// and 7 more stores...
```

I see two possible problems:
- Imagine you write a new **Store** which does something when the Dashboard is shown. You have to know exactly all the actions which lead to a redirection to the dashboard. Imagine how easy should be to write only `"SHOW_DASHBOARD"` instead.
- Imagine you want to change the redirection of the `AddNameAndCreateFirstPost` screen to the `EditPost`screen. You have to go find and change the `"CREATE_FIRST_POST_FORM_SUBMITTED"` in 10 different files. Imagine how easy it should be to just change `"SHOW_DASHBOARD"` to `"SHOW_EDIT_POST"` instead.


About describing what the user did, you said:
*@kyldvs "Generally an action fired should correspond to what the user is doing, it doesn't correspond to what you want a store to do."*

In my `AddNameAndCreateFirstPost` screen the user, you are right, the user did this action:  `"CREATE_FIRST_POST_FORM_SUBMITTED"`.

But when he is in the `EditProfile` screen, the action is `"USER_NAME_CHANGED"` and not `"PROFILE_FORM_SUBMITTED"`. And in the `CreatePost` screen the action is `"NEW_POST_CREATED"` and not `"NEW_POST_FORM_SUBMITTED"` as well.

So if we can describe what has happened in those terms, why `"USER_NAME_CHANGED" && "NEW_POST_CREATED" && "SHOW_DASHBOARD"` instead of `"CREATE_FIRST_POST_FORM_SUBMITTED"` is wrong to describe what the user just did?

**Comment by kyldvs** [comment]
Generally we try to use `hasChanged()` in order to prevent needing to have large lists of actions that we need to maintain.

https://github.com/facebook/flux/blob/master/src/stores/FluxStore.js#L117

While I don't completely understand the purpose of all of your stores, a revised structure may look more similar to this:

```javascript
class RouteStore extends FluxReduceStore {
  getInitialState() {
    return '/login';
  }

  reduce(state, action) {
    switch (action.type) {
      case 'show_dashboard':
      case 'create_first_post_form_submitted':
      case 'login_successful':
        // updating of the url omitted
        return '/foo/dashboard';

      default:
        return state;
    }
  }
}

class BreadCrumbStore extends FluxReduceStore {
  ...
  reduce(state, action) {
    this.getDispatcher().waitFor([RouteStore.getDispatchToken()]);
    // The current route changed, so we need to update the breadcrumb
    if (RouteStore.hasChanged()) {
      const route = RouteStore.getState();
      switch (route) {
        case '/login':
          return loginBreadCrumbs(state);

        case '/foo/dashboard':
          return dashboardBreadCrumbs(state);

        default:
          return fourOhFourBreadCrumb(state);
      }
    }
    return state;
  }
}
```

In this way you can build dependencies between the data within stores. This enables you to have stores depend on the data in another store rather than the entire list of actions that may cause a specific store to change.

Sometimes it is necessary to maintain two larger list of actions within separate stores, but we've not found it all that common even though we have well over 200 stores at this point.

**Comment by LuisHerranz** [comment]
Thanks again @kyldvs for taking the time to keep answering me in this regard.

I understand this solution, and it works well in many situations. I have used it myself in non-Flux applications. 

Now... I know I am giving this a hard time, but I still have concerns regarding this solution.

1. To make my example work, you are getting rid of Flux. 
Imagine another person creates a new **Store** in the future. He registers for `"SHOW_DASHBOARD"` and sometimes it doesn't work because the user is on the dashboard but `"SHOW_DASHBOARD"` is not triggered. You have to explain him that even though `"SHOW_DASHBOARD"` exists, he can't use it because that part of the app is outside Flux and he has to use `RouteStore.hasChanged()` instead of `Dispatcher.register()` and make his **Store** dependent on `RouteStore`.

2. To avoid chaining notifications in the Dispatcher, you are actually using a different notification system: `RouteStore.hasChanged()` instead of `Dispatcher.register()`. 
If you refactor your code and use `Dispatcher.register()` instead, you end up dispatching in the middle of a dispatch. So it looks like changing the notification system only has the benefit of bypassing that rule. `RouteStore.hasChanged()` doesn't add any other benefit to the `Dispatcher` system.

3. If one of the Flux principles is easy debugging and you look at the flow of your user actions, you will see things like 
```
"SHOW_LOGIN" => "LOGIN_SUCCEED" => "SHOW_CREATE_FIRST_POST" => 
=> "CREATE_FIRST_POST_FORM_SENT" => "SHOW_EDIT_POST" => "DELETED_POST"
```
All the `"SHOW_DASHBOARDS"` are hidden here, even if the user was actually in the dashboard screen twice in this flow, after `"CREATE_FIRST_POST_FORM_SENT"` and after `"DELETED_POST"`. To know what's really going on, you would have to implement new logging features to include the `RouteStore.hasChanged()` notifications.

----

So, after all our conversation, what I am wondering is... why is it so wrong to do THIS, that you are trying so hard to avoid it? 

```javascript
var handleClick = function() {
  Dispatcher.dispatch('PROFILE_NAME_CHANGED');
  Dispatcher.dispatch('SHOW_DASHBOARD');
};
```

Why is it so wrong that if the user did a `MultiTask` in one step, you write instead `SmallTask AND SmallTask`? What type of problems can it lead to?

I can imagine other workarounds in the UI side. For example, if I give the user a `SAVE` button with a  `"PROFILE_NAME_CHANGED"` dispatch. Then I give him a `NAME SAVED!` hint and a new button `GO TO DASHBOARD` with a `"SHOW_DASHBOARD"` dispatch.  That would work just fine in Flux and we won't be having this conversation.

In the way I see it, dispatching `SmallTask AND SmallTask` I am just saving the user that second click. Why is it so wrong to save him a click when he actually wants to save his name and go to the dashboard in one step? You are not chaining actions, your actions are still easy to trace and debug, your log is fine, all your app parts use Flux. So what are you seeing I am not?

----

I am sorry, I think it looks like I am pretty sure that "my solution" is right and I am trying hard to defend it, but I'm not. I really love Flux and all its principles. I am just trying to understand Flux in this scenario. 

I just asked in the first place because I never saw something like this before and wanted to know your impressions.

Many thanks for your help here. I really appreciate it.

**Comment by sterpe** [comment]
One of the problems I found is that you begin having to push increasing amounts of state into your dispatch payloads so that the backing stores can differentiate between event targets.  This becomes necessary as the application ui interaction becomes non-trivial.

My 2 cents

**Comment by kyldvs** [comment]
```
var handleClick = function() {
  Dispatcher.dispatch('PROFILE_NAME_CHANGED');
  Dispatcher.dispatch('SHOW_DASHBOARD');
};
```

Isn't the worst thing in the world. It shouldn't be necessary but sometimes it's easier to do things this way. I know we sequentially dispatch actions in several places.

I don't have anything else to add other than my previous comments. Going to close this out. If you'd like to discuss this further please re-open.

**Comment by luisherranz** [comment]
Thanks @kyldvs. I've using that approach since then and so far it has worked fine.
