### ISSUE TITLE
flow include files not usable to get flow typing

### ISSUE THREAD

**Issue by kyldvs** [facebook/flux#297]
See conversation from @lukescott in #285.

Flow types do not appear to be able to be included properly in the .flowconfig.

**Comment by lukescott** [comment]
So far I've observed the following:
- The todomvc example uses `[include]`, when http://flowtype.org/docs/third-party.html talks about `[lib]`
- The thirt-party docs mentions `declare`. `node_modules/flux/flow/include` contains actual source code, which may explain why this doesn't work.
- The npm module has pre-compiled in `node_modules/lib`, which is why `node_modules/flux/flow/include` is needed.

Is flux out of date with flow? Couple of possible solutions come to mind:
- Update flux/flow to use declare
- Enable babel's flow comments plugin to keep type annotations in the compiled source

**Comment by zpao** [comment]
This overlaps with stuff I've been doing with fbjs. Currently we ship the original src files for flow to pick up and parse. We do this because there are some cases where the inline comments don't work well, namely polymorphic classes. With the next Flow release, it will support shipping a declaration file next to the original source so that we don't have to do special things with includes in `.flowconfig` files, so we'll do that for fbjs and I'll say we should do the same thing here.

**Comment by Daniel15** [comment]
> Currently we ship the original src files for flow to pick up and parse.

Do we actually include the src files in the npm package? If so, we should be able to close #272

**Comment by zpao** [comment]
Only in fbjs. Not here afaik. But the infra that's being worked on for fbjs can be used here.
