### ISSUE TITLE
[Flux Utils] Changes fired between getInitialState and componentDidMount do not cause updates

### ISSUE THREAD

**Issue by lovedota** [facebook/flux#316]
Hi guys.
I have a *Component*. I want after  **componentDidMount** , call action to get all the *links*. But it does not work, so I have to use *setTimeout* to make it work.

``` ts
class MainComponent extends React.Component<any, State> {
    static getStores(): Array<Store> {
        return [MainStore];
    }

    static calculateState(prevState?: State): any {
        console.log("MainComponent: calculateState");
        let state = MainStore.getState();

        return {
            links: state.get("links"),
            currentComponent: state.get("currentComponent")
        };
    }

    componentDidMount() {
        // Call actions after MainComponent init Store
        setTimeout(() => {
            MainActions.getLinks();
        });
    }
}

```

**Comment by kyldvs** [comment]
This works for me. Make sure you are registering your store with the dispatcher prior to componentDidMount.

**Comment by bannaN** [comment]
It might be that we are using a anti pattern, but I have i similar problem.

We are creating a fluxcontainer, and in componentDidMount we are  dispatching a action to populate certain state properties in a store.

Since the flux container calls the base.prototype.componentDidMount before it sets up the change listener any action I dispatch will not be reflected in the UI since the change event is not picked up by the component. Could the call to the component defined componentDidMount method be moved to after the fluxcontainer has attached its listener? Or is it some better way of solving this particular usecase?

**Comment by kyldvs** [comment]
Aha, thanks for looking into this @bannaN! Yes there is a timing gap where changes fired between `getInitialState()` and `componentDidMount()` are lost.

**Comment by kyldvs** [comment]
Fixed here: https://github.com/facebook/flux/commit/ba9d6b7296d572ed7d1af5a54b8d0637f3986b84

**Comment by bannaN** [comment]
Nice, thanks! This will let me remove some setTimeout hacks. Really appreciated!

**Comment by lovedota** [comment]
@kyldvs  thanks please release it to npm
