### ISSUE TITLE
Should we call Store function in Action ?

### ISSUE THREAD

**Issue by lovedota** [facebook/flux#331]
Hi guys
I have a case. I need to check if the Id is valid from Store or not, but I need to call Store function here. Is it a good practice ? Thanks !

Action.js

```js
save(id) {
     //Check if is valid or not
     if (Store.checkValid(id)) {
          api.save(id).then(dispatchSuccess)
     }
     else {
          dispatchError();
     }
}
```

**Comment by kyldvs** [comment]
Seems okay to me. An alternative is to just check before firing the action

```
if (Store.checkValid(id) {
  Action.save(id);
}
```

**Comment by lovedota** [comment]
@kyldvs  but it will not a good practice for
Action -> Dispatcher -> Store -> View
We call Store in Action is look like a loop back.

**Comment by kyldvs** [comment]
The one way flow is most important for the mutation path. The action is still flowing through the system in one direction.

I do think it is better to not use stores within action creators, but I do not have that strong of an opinion either way.

Ideally your action creators would be "pure" functions that generate the action based only on their input, but action creators are inherently not pure because they dispatch an action as a side effect. (If you are using Redux though actions creators are pure functions!)

This is probably ideal:

```js
changeCurrentUsersName(id, name) {
  Dispatcher.dispatch({
    type: 'change_current_user_name',
    id,
    name,
  });
}
```

But you may find that you do this everywhere:

```js
changeCurrentUsersName(CurrentUserStore.getID(), this.state.name);
```

So you *could* refactor it to this for ease of use, but I do think it's slightly worse code:

```js
changeCurrentUsersName(name) {
  Dispatcher.dispatch({
    type: 'change_current_user_name',
    id: CurrentUserStore.getID(),
    name,
  });
}
```

Hope that helps.

**Comment by lovedota** [comment]
@kyldvs 
Sorry, but how about using Store in View to follow one way direction. Is it a better way ? 

```
onClick() {
    let name = ReactDOM.findDOMNode(this.refs['username']).value;
    action.changeCurrentUserName(CurrentUserStore.getID(), name);
}
```

**Comment by kyldvs** [comment]
Yeah that is what I was trying to communicate in my second code block :)

**Comment by lovedota** [comment]
@kyldvs  
Yeah Thanks, So can you update FLUX document about good practice for using in Action, Store, Views
