### ISSUE TITLE
NPM package 3.0 release required

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [facebook/flux#343]
When you plan to release a new version?

**Comment by kyldvs** [comment]
Working through a few more changes internally, then will sync and release. Should be this week.

**Comment by alexeyraspopov** [comment]
@kyldvs I hope it's the right place to ask. What's the benefit of having React as a dependency?

**Comment by kyldvs** [comment]
It was added as a dependency for `FluxContainer.createFunctional()`. It is not a dependency for Dispatcher, so any build step/bundler/etc would not include it if you just use Dispatcher.

**Comment by alexeyraspopov** [comment]
> It is not a dependency for Dispatcher, so any build step/bundler/etc would not include it if you just use Dispatcher.

Valid point.

Still, I can imagine a conversation in a team, where additional (unused) dependencies (like react for angular based project) will increase `npm install` time which is not good anyway. Does `createFunctional` make life simpler so the trade off (additional dependency) worth it?

The same question for `FluxMapStore` and its `immutable` dependency, but I would start a separate topic for this.

I have a project based Flux and trying to use the same experience in a huge angular based project. But now I see small concerns that my team can get when we will discuss it.

**Comment by kyldvs** [comment]
Okay that makes sense, I can update it to a peer dependency.

I think createFunctional is much nicer than just create. It allows you to use react's functional stateless components which cuts down on boilerplate a lot. Hopefully as a peer dependency this won't really be an issue.

Yeah I struggle a lot with FluxMapStore being the only reason for adding immutable as a dependency. I was strongly considering removing it in 3.0, and maybe I still will.

My reasons for keeping it were:

1) to demonstrate how to extend FluxReduceStore and add functionality to it (getters)
2) encourage people to use full Immutable data structures rather than their mutable counterparts. (Immutable.Map vs Map)

It seems reasonable to kill FluxMapStore and add a small example for it rather than bloating this project though.

**Comment by alexeyraspopov** [comment]
> Yeah I struggle a lot with FluxMapStore being the only reason for adding immutable as a dependency. I was strongly considering removing it in 3.0, and maybe I still will.

Yeah, we definitely on the same page :)

In my experience, FluxMapStore doesn't have such a difference from FluxReduceStore, because in most cases you still need to provide `getInitialState()` where you return your own, not empty `Immutable.Map` (with the actual initial state). Also, with stores that work with complex collections, you'd better add your own getters that will hide the complexity of items by using simple `map`, `filter` or `reduce`. (i.e. `getPendingJobs()`, `getUnreadMessages()`, `getNewProjectsCount()`).

> It seems reasonable to kill FluxMapStore and add a small example for it rather than bloating this project though.

I'd be happy to help you with first part :)

"Guides" section on the website could be the best place for such example/article, I think.

**Comment by alexeyraspopov** [comment]
@zpao @kyldvs, as a result of this discussion I've opened #348 and #349.

**Comment by rgoldfinger** [comment]
+1 for publishing the current version to NPM.

**Comment by kyldvs** [comment]
Sorry this took so long, I wanted to get documentation/examples updated before the release as well which is why I waited so long. Will just go ahead and bump the version and followup with new examples later.

https://www.npmjs.com/package/flux is at 3.0.0 now
