### ISSUE TITLE
Cannot assign to read only property '__esModule' of #<Object>

### ISSUE THREAD

**Issue by jdelStrother** [facebook/flux#373]
Our error-reporter keeps catching exceptions that I've been unable to reproduce locally:

`Cannot assign to read only property '__esModule' of #<Object>`

from this location : https://github.com/facebook/flux/blob/master/dist/Flux.js#L92

I'm struggling to imagine how/why this might happen, but wondered if anyone here had run into anything similar?

We're using webpack to build this, so the `exports` object there ought to be a regular empty `{}` object.

**Comment by kyldvs** [comment]
This sounds like an issue in old browsers: http://stackoverflow.com/questions/35461830/cannot-assign-to-read-only-property-esmodule

**Comment by jdelStrother** [comment]
Perhaps, though I can't see how the error mighty occur - the `exports` object passed in is a plain object literal, with no defineProperty additions.

**Comment by mockdeep** [comment]
@jdelStrother what browser user agent do you see this error coming in from? We got it from the old Android stock browser. It's probably not related to Flux specifically so much as the transpiling that happens with Webpack. We opted to deprecate support for the browser since it's 0.1% of usage on our platform.

**Comment by jdelStrother** [comment]
Yeah, sounds plausible.   We dropped support for pre-es5 browsers a few months back, and don't think we've seen this error since.

**Comment by kyldvs** [comment]
Closing this out as it's quite old
