### ISSUE TITLE
Using data from Stores directly within a component

### ISSUE THREAD

**Issue by salmankhann** [facebook/flux#408]
Conside a Component K that is deeply nested in the component tree of various components for example and takes around 7 props in order to render.

For Example,

A
|__ B
|____C
|_______D
|________K

and
P
|__ Q
|____R
|_______S
|__________K

and so on where A,B,C,D,P,Q,R,S are all components.

calculateState is used in Components A & P to get data from various stores.

Because K needs 7 props this creates 2 problems
1. We need to tediously pass these 7 props all the way from the top (because the top components A & P interact with stores and pass data all the way down to K. This creates a lot of noise because no other components need this 7 pieces of data.
2. Even if the verbosity and tediousness from (1) is ignored, the real problem occurs when the props of K are modified later on in the development lifecycle by adding, removing or changing any of the 7 props. In this case it becomes difficult to trace all the various component trees that are affected and manually modify these props being passed especially if K is used in many different component trees.

Instead I was thinking if I could directly import stores that K needs and call getState() to get whatever pieces of data I need and use it locally.

Am I on the right track?

Thanks!

**Comment by kyldvs** [comment]
Hi, great question!

This is a common problem -- having to pass props through a lot of components -- that I think Flux solves really well. The idea is to create containers at multiple levels in your tree where it makes sense to do so. Containers are view components that get information directly from stores.

So in your example component A and P are probably already containers, and then B, C, D, Q, R, S, K sound like they are not containers. Instead of just having A and P be containers, make K a container also. Then K is not dependent on information from its parent components. This will make it easier to refactor everything above and below K in the tree.

Container can also accept props if necessary (although this will hurt performance slightly and is not recommended), so you could even pass 1-2 props from D -> K or S -> K if needed and then get the remaining 5-6 pieces of data from stores.
