### ISSUE TITLE
Improvement : Error on dispatching a mutable state in Reduce Store

### ISSUE THREAD

**Issue by CarolineBoyer** [facebook/flux#423]
First of all, thank you so much for the work you are doing on Flux. I just came back to JS/flux after a while, and discovered the ReduceStore class. Great adding, allowing the user to not care about the emitChange.

Well, not that good... Because it seems the ReduceStore is not triggering emitChange if the data is not immutable ( or something like this). It would be a great improvement to have a error/message/smoke signal from Flux to tell you why it is not emitChange even when you are actually changing.

Here is an exemple of what I am trying to say. I have been working on a tree data structure. And some action ( i'll call it A_CERTAIN_ACTION for you guys) changes the name of the Node.

```javascript
reduce(state, action) {
   switch (action.action) {
    ...
            case ActionTypes.A_CERTAIN_ACTION:
               console.log(state.customGetIn("pathToNode") ) 
               // {NODE : ..., ... , "name": oldName,... }
                state.customSetIn( "pathToNode", "name", action.name );
                console.log(state.customGetIn("pathToNode") ) 
               // {NODE : ..., ... , "name": theNewNameGivenByAction.name,...}
                return state;
```

So the state has changed. I was to guess the function isEqual should be false and therefore this condition ( https://github.com/facebook/flux/blob/520a60c18aa3e9af59710d45cd37b9a6894a7bce/src/stores/FluxReduceStore.js#L98) should be triggered.
But no emitChange is thrown. Which I guess is why my react component aren't rerendering (even if they do on some other actions). 

I am guessing I did something wrong ( not the point, but if you have an idea :) thought it's more of a stackoverflow question ), it would be great to have at least some word from flux saying emitChange wasn't triggered because of bad data handeling/coding like I probably did or something. ><
Especially for people who are new to Flux :)

Happy fluxing everybody !

**Comment by kyldvs** [comment]
Hey @CarolineBoyer, glad you are liking (maybe? :P) the ReduceStore class after getting back into Flux.

I believe I understand your question, and unfortunately due to how Flux works it's essentially impossible to provide developer hints that warn you if you aren't emitting changes properly. I'll try to explain why.

- Every store gets **every** action, but each store typically only changes state for a **subset** of those actions.
  - This means that many actions are fired where the store (correctly) does not change state at all. This is actually the most common case. Printing some kind of warning because a store did not change state would be very, very noisy.
- The `areEqual` function is called on every single action, it is a hot code path, that means it needs to be quick.
  - This prevents us from doing a deep equality check between the old and new state by default and warning/emitting when they differ. That's why we use `===` and expect state to be immutable. If we didn't expect this `ReduceStore` would be terribly slow to the point that it's unusable.

These two things make it very hard to provide warnings at an appropriate time for the issue you're describing.

The easiest fix to make sure you never run into this issue is to **always** use an immutable structure for the state of the store. I very highly recommend using immutable state for several reasons. Two important ones are:

1. It fixes this issue :)
2. Using mutable state violates one of the core principles of Flux. It means that you can have setters modifying the internal state of the store outside of the Flux system. This means that the state of the store could change without an action being handled, thus there is no opportunity to notify subscribers of the changes. This can put your application in very broken states.

Hope this helps! If anything I said is unclear please keep asking questions here and I'll try to clarify.

**Comment by CarolineBoyer** [comment]
Thank you for the time you took answering this !
Oh damn ! I forgot that every store gets every action, even those you haven't implemented ! It would truly be a nightmare to trigger a message only in those that actually implement the action... You are right sorry.

Well, I understood that state had to be immutable... But when the nature of the action itself is to change the state ( here a small leaf, in a vast tree), I didn't see myself recreating a new tree with that little change. 

I'll keep on looking for the "immutable" way of updating my tree.

Thank you !

**Comment by kyldvs** [comment]
>  I didn't see myself recreating a new tree with that little change.

Typically this isn't as slow as you might expect. Especially if you can take advantage of libraries like https://facebook.github.io/immutable-js/ which will do a lot of work trying to reuse objects where possible.

Specifically using a record for the node class in your tree may work: https://facebook.github.io/immutable-js/docs/#/Record
