### ISSUE TITLE
Example using Store instead of ReduceStore

### ISSUE THREAD

**Issue by spacedarcy** [facebook/flux#448]
Hi, just wondering why there aren't any examples using the plain Store class, or an explanation of the differences between it and ReduceStore.

**Comment by kyldvs** [comment]
That is because we strongly recommend using `ReduceStore` instead of the plain `Store`. The `Store` class can be thought of as utilities to help implement `ReduceStore`. `Store` provides functionality like connecting to a dispatcher, adding listeners, and emitting changes.

The only example I would recommend for using `Store` is the implementation of `ReduceStore` itself: https://github.com/facebook/flux/blob/master/src/stores/FluxReduceStore.js
